DATALOADER:
  TRAIN_X:
    BATCH_SIZE: 8
  TEST:
    BATCH_SIZE: 100
  NUM_WORKERS: 4

OPTIM:
  NAME: 'sgd'
  LR: 0.001
  MAX_EPOCH: 50
  STEPSIZE: (20,)
  GAMMA: 0.1
  LR_SCHEDULER: 'single_step'

TRAINER:
  VANILLA2:
    MIX: 'random'

